hyperparameters:
  batch_size: 4
  n_epochs: 2
  lr: 0.001
  seed: 42

early_stopping:
  patience: 5        # matches config.early_stopping.patience in train.py

trainer:
  limit_train_batches: 0.2  # matches config.trainer.limit_train_batches in train.py
